### ISSUE TITLE
MAJ/associer Zoom

### ISSUE THREAD

**Issue by ccoulombe** [calculquebec/CQORC#17]
Une fois le zoom créé par l'API de Zoom, il faut associer le webinaire à l'événement Eventbrite

```
    {
     "data":{
        "webinar_url":{
           "text":"my webinar",
           "url":"http://zoom.us/1234"
        },
        "image":{
           "type":"image",
           "image_id":"63131771"
        },
        "title":{
           "text": "Optional Title",
        },
        "instructions":{
           "text": "Instructions to join the webinar",
        }
     },
     "type": "webinar"
}```

**Comment by mboisson** [comment]
Le Zoom ID peut être récupéré pour un cours donné à partir de la classe Calendar de CQORCcalendar, via le course_id: 

```
import CQORCcalendar

calendar = CQORCcalendar.Calendar(config, args)
course = calendar[args.course_id]
zoom_id = course['zoom_id']
```

**Comment by mboisson** [comment]
Hum, je l'ai implémenté, mais ça ne marche pas, ça rajoute un webinaire générique avec l'URL Zoom, et non pas un webinaire Zoom connecté à l'événement.

**Comment by mboisson** [comment]
Après inspection des données pour 2 événements différents, il y a deux éléments qui sont problématiques et qu'on n'a pas: 
```
                "zoom_sdk_signature": {
                    "text": "S3c4WjZPWFRTTGlJeTRXWWJOVDIzdy44NzU4NjIyOTY1Mi4xNzI0MzM5OTU3NzU4LjAueDZtRXdyVzdDOHpiZ0NiZVlnOWQvd25weks3QjZCeTlxVWIrZERreEZPZz0"
                },
``` 
et
```
                "zoom_mapping_id": {
                    "zoom_mapping_id": "9027669"
                },
``` 
qui changent d'un événement à l'autre, sans façon évidente de les déduire.... 

Je crois que ça ne sera pas possible d'associer les Zoom à EventBrite automatiquement. Il faudra les associer manuellement après la création.

**Comment by mboisson** [comment]
J'ai posé la question sur https://groups.google.com/g/eventbrite-api

**Comment by mboisson** [comment]
Je ferme en attendant.
